name: deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies (Backend)
        run: |
          cd ./server
          npm i
      - name: Install dependencies (Frontend)
        run: |
          cd ./client
          npm i
      - name: Lint frontend
        run: |
          cd ./client
          npm run lint
      - name: Lint backend
        run: |
          cd ./server
          npm run lint
   

   
