name: deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies (Backend)
        run: |
          cd ./server
          npm i
      - name: Install dependencies (Frontend)
        run: |
          cd ./client
          npm i
      - name: install dependencies (Playwright)
        run: npm i
      - name: Lint frontend
        run: |
          cd ./client
          npm run lint
      - name: Lint backend
        run: |
          cd ./server
          npm run lint
      - name: Build frontend
        run: |
          cd ./client
          npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: |
          cd ./client/tests
          npx playwright test
   
   
   

   
